frequency: 0.5
sensors:
  - channel: 0
    unit: V
    name: Battery Charge
    limit: 12

  - channel: 1
    name: Solar Supply
    unit: A
    limit: 20

  - channel: 2
    name: DC Load
    unit: A
    limit: 22.5

  - channel: 3
    name: AC/DC Inverter Load
    unit: A
    limit: 20
