vref: 3.3
frequency: 0.5
sensors:
  - channel: 0
    name: Battery (V)
    range: 12

  - channel: 1
    name: Solar Output (A)
    range: 20

  - channel: 2
    name: DC Draw (A)
    range: 22.5

  - channel: 3
    name: AC/DC Inverter Draw (A)
    range: 20
