vref: 3.3
bits: 10
frequency: 0.5
channels:
  - channel: 0
    name: Battery Voltage
    type: voltage
    max: 12

  - channel: 1
    name: Solar Output
    type: current
    max: 20

  - channel: 2
    name: DC Bus
    type: current
    max: 22.5

  - channel: 3
    name: AC/DC Inverter
    type: current
    max: 20
